# Generated by Django 6.1 on 2026-08-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('issued_quantity', models.PositiveIntegerField(default=0)),
                ('damaged_quantity', models.PositiveIntegerField(default=0)),
                ('lost_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='books.book')),
            ],
            options={
                'ordering': ['book__title'],
            },
        ),
    ]
