# Generated by Django 6.1 on 2026-08-24 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_title'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='title_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_books', to='books.title'),
        ),
    ]