# Generated by Django 6.1 on 2026-08-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_barcode_book_branch_book_condition_book_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]