# Generated by Django 6.1 on 2026-09-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='title',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
